package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Echo'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Echo")
    name = "Echo"

    params {
        param("env.LANG", "en-us")
        param("env.DEFAULT_LANG", "en-us")
    }

    vcs {
        root(RelativeId("HttpsGithubComMburmistrovTeamcityS3clientAppSampleRefsHeadsMain"))
    }

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """
                #!/bin/bash
                set -e
                
                if [ "${'$'}DEFAULT_LANG" == "en-us" ]; then
                    INDEX_NAME="index_${'$'}LANG"
                elif [ "${'$'}DEFAULT_LANG" == "zh-cn" ]; then
                    INDEX_NAME="index_cn_${'$'}LANG"
                else
                    echo "Unsupported default language: ${'$'}DEFAULT_LANG"
                
                fi
                
                echo "The INDEX_NAME is: ${'$'}INDEX_NAME"
                
                # set last_commit_tag = git describe --tags %build.vcs.number%
                #                echo "123"
                #                echo "321"
                #                if [ %last_commit_tag% == "tezzzme" ]; then
                #                  echo "has tezzzme tag"
                #                else
                #                  echo "dont have tezzzme tag"
                #fi
            """.trimIndent()
        }
    }
}))

