package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Echo'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Echo")
    name = "Echo"

    params {
        param("env.LANG", "en-us")
        param("last_commit_tag", "123")
        param("env.DEFAULT_LANG", "en-us")
    }

    vcs {
        root(RelativeId("HttpsGithubComMburmistrovTeamcityS3clientAppSampleRefsHeadsMain"))
    }

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """
                #!/bin/bash
                set -e
                
                LAST_COMMIT_TAGS=${'$'}(git describe --tags --abbrev=0)
                echo "123"
                echo "${'$'}LAST_COMMIT_TAGS"
                echo "321"
                if [ "${'$'}LAST_COMMIT_TAGS" == "tezzzme" ]; then
                  echo "has tezzzme tag"
                 else
                  echo "dont have tezzzme tag"
                fi
            """.trimIndent()
        }
    }
}))

