package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'I18nPush'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("I18nPush")
    name = "i18n push"

    vcs {
        root(RelativeId("HttpsGithubComMburmistrovTeamcityS3clientAppSampleRefsHeadsMain"))
    }

    steps {
        script {
            name = "i18n push"
            id = "i18n_push"
            scriptContent = """
                if [ -e "./i18n-staging-branches/%teamcity.build.branch%" ]; then
                  # npm run i18n-push
                  echo "RUN i18n push"
                else
                  echo "🚀 skip i18n push"
                fi
            """.trimIndent()
            dockerImage = "node:18.19.1"
        }
    }

    dependencies {
        snapshot(RelativeId("InstallDeps")) {
        }
    }
}))

