package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'I18nPull'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("I18nPull")
    name = "i18n pull"

    vcs {
        root(RelativeId("HttpsGithubComMburmistrovTeamcityS3clientAppSampleRefsHeadsMain"))
    }

    steps {
        nodeJS {
            name = "i18n pull (1)"
            id = "i18n_pull_1"
            shellScript = """
                if [ -e "./i18n-staging-branches/%teamcity.build.branch%" ]; then
                  npm run i18n-pull
                else
                  echo "🏎️ skip i18n pull"
                fi
            """.trimIndent()
            dockerImage = "node:18.19.1"
        }
    }

    dependencies {
        snapshot(RelativeId("I18nPush")) {
        }
    }
}))

